### PR TITLE
Remove broken run_test.py

### PR DESCRIPTION
**Pull request by mingwandroid**

### CODE REVIEW

**Comment by jakirkham** [comment]
Why do you say this is broken? Wasn't failing before FWICT. 😕

**Comment by mingwandroid** [comment]
It's broken because conda-env is an empty package that doesn't set any CONDA_PREFIX env var.

**Comment by jakirkham** [comment]
FWICT `CONDA_PREFIX` is set by running `activate`, which `conda-build` does before entering the test phase. Why would this depend on this package (or its contents)? 😕

**Comment by mingwandroid** [comment]
If that is a facility of conda then why are you testing it in conda-env? This package used to be responsible for setting env vars (to the best of my knowledge) but it isn't anymore.

It has expired and only still exists to keep the solver happy.

**Comment by jakirkham** [comment]
We had to have some sort of test for this package. All we could think of was a test for its existence, which is what this test is. This was created specifically for 2.6.0.

I thought `conda-env` provided the `env` subcommand for `conda` and thus supported environment creation and inspection in a variety of ways, no? In any event, it is clear this package doesn't do anything any more.

**Comment by mingwandroid** [comment]
Why do you need a test for an empty package? Is this some sort of 'tests are good' thing taken too far?

I have been trying to bootstrap a conda-forge based miniconda via cross-compilation and since this is a dependency of conda itself and since bootstrapping means by definition that conda does not exist yet this test makes that impossible.

**Comment by jakirkham** [comment]
I see. Thanks for the info. What if we just skip this test if `CONDA_PREFIX` is not defined? Would that solve the issue for you?

**Comment by mingwandroid** [comment]
Maybe? I still don't get the need to test an empty package though!

**Pull request merged**
